
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='mbctl',
    version='0.1.0',
    python_requires='==3.*,>=3.6.0',
    author='lrossett',
    author_email='lrossett@redhat.com',
    entry_points={"console_scripts": ["mbctl = mbctl.cli:main"]},
    packages=['mbctl', 'mblib', 'mblib.builds', 'mblib.version'],
    package_dir={"": "src"},
    package_data={},
    install_requires=['gitpython==3.*,>=3.1.14', 'requests==2.*,>=2.25.1', 'requests-kerberos==0.*,>=0.12.0', 'setuptools-rust==0.*,>=0.12.1', 'terminaltables==3.*,>=3.1.0'],
    extras_require={"dev": ["dephell==0.*,>=0.8.3", "pytest==5.*,>=5.2.0", "pytest-mock==3.*,>=3.5.1", "pytest-sugar==0.*,>=0.9.4", "requests-mock==1.*,>=1.8.0"]},
)
